### Base Objectives ###
1. Deleting redundant columns
2. Renaming Columns
3. Cleaning Individual Coulmns
4. Removing null Values
5. Check for further transformations

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("C:\\Users\\akash\\OneDrive\\Desktop\\Python\\Datasets\\Airbnb_Open_Data.csv")

C:\Users\akash\AppData\Local\Temp\ipykernel_26468\3165231677.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("C:\\Users\\akash\\OneDrive\\Desktop\\Python\\Datasets\\Airbnb_Open_Data.csv")

In [3]:
df.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [4]:
df.isna().sum()

id                                     0
NAME                                 250
host id                                0
host_identity_verified               289
host name                            406
neighbourhood group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country code                         131
instant_bookable                     105
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
minimum nights                       409
number of reviews                    183
last review                        15893
reviews per month                  15879
review rate number                   326
calculated host listings count       319
availability 365                     448
house_rules                        52131
license                           102597
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

As we can see that the license column has only 2 non null values we are going to drop this in order to use functions like drop NA.

In [6]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [7]:
columns_to_drop = ['Construction year','last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license']

In [8]:
df.drop(columns=columns_to_drop, inplace = True)

In [9]:
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,price,service fee,minimum nights,number of reviews
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,$966,$193,10.0,9.0
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,$142,$28,30.0,45.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,$620,$124,3.0,0.0
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,$368,$74,30.0,270.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,$204,$41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,$844,$169,1.0,0.0
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,$837,$167,1.0,1.0
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,$988,$198,3.0,0.0
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,$546,$109,2.0,5.0
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,"$1,032",$206,1.0,0.0

### Renaming Columns

In [10]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'price', 'service fee', 'minimum nights', 'number of reviews'],
      dtype='object')

In [11]:
new_column_name = []
for i in df.columns:
    new_column_name.append(i.upper())

In [12]:
new_column_name

['ID',
 'NAME',
 'HOST ID',
 'HOST_IDENTITY_VERIFIED',
 'HOST NAME',
 'NEIGHBOURHOOD GROUP',
 'NEIGHBOURHOOD',
 'LAT',
 'LONG',
 'COUNTRY',
 'COUNTRY CODE',
 'INSTANT_BOOKABLE',
 'CANCELLATION_POLICY',
 'ROOM TYPE',
 'PRICE',
 'SERVICE FEE',
 'MINIMUM NIGHTS',
 'NUMBER OF REVIEWS']

In [13]:
 df1=df.copy()

In [14]:
df1.columns= new_column_name

In [15]:
df.columns= new_column_name

In [16]:
df1

,ID,NAME,HOST ID,HOST_IDENTITY_VERIFIED,HOST NAME,NEIGHBOURHOOD GROUP,NEIGHBOURHOOD,LAT,LONG,COUNTRY,COUNTRY CODE,INSTANT_BOOKABLE,CANCELLATION_POLICY,ROOM TYPE,PRICE,SERVICE FEE,MINIMUM NIGHTS,NUMBER OF REVIEWS
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,$966,$193,10.0,9.0
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,$142,$28,30.0,45.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,$620,$124,3.0,0.0
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,$368,$74,30.0,270.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,$204,$41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,$844,$169,1.0,0.0
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,$837,$167,1.0,1.0
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,$988,$198,3.0,0.0
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,$546,$109,2.0,5.0
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,"$1,032",$206,1.0,0.0

### Handling Duplicates ###

In [17]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
102594     True
102595     True
102596     True
102597     True
102598     True
Length: 102599, dtype: bool

In [18]:
df.duplicated().sum()

541

In [19]:
df.tail()

,ID,NAME,HOST ID,HOST_IDENTITY_VERIFIED,HOST NAME,NEIGHBOURHOOD GROUP,NEIGHBOURHOOD,LAT,LONG,COUNTRY,COUNTRY CODE,INSTANT_BOOKABLE,CANCELLATION_POLICY,ROOM TYPE,PRICE,SERVICE FEE,MINIMUM NIGHTS,NUMBER OF REVIEWS
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,$844,$169,1.0,0.0
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,$837,$167,1.0,1.0
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,$988,$198,3.0,0.0
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,$546,$109,2.0,5.0
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,"$1,032",$206,1.0,0.0

In [20]:
duplicate_rows = df[df.duplicated()]

In [21]:
print(f"Total duplicate rows: {duplicate_rows.shape[0]}")

Total duplicate rows: 541

In [22]:
duplicate_rows.head()

,ID,NAME,HOST ID,HOST_IDENTITY_VERIFIED,HOST NAME,NEIGHBOURHOOD GROUP,NEIGHBOURHOOD,LAT,LONG,COUNTRY,COUNTRY CODE,INSTANT_BOOKABLE,CANCELLATION_POLICY,ROOM TYPE,PRICE,SERVICE FEE,MINIMUM NIGHTS,NUMBER OF REVIEWS
102058,35506831,Master Bedroom with private Bathroom & Balcony,55110690425,unconfirmed,UZeyir,Queens,Maspeth,40.74056,-73.90635,United States,US,True,strict,Private room,$706,$141,1.0,1.0
102059,35507383,Cozy 2 br in sunny Fort Greene apt,80193772189,verified,Sally,Brooklyn,Fort Greene,40.68701,-73.97555,United States,US,False,flexible,Private room,$651,$130,3.0,38.0
102060,35507935,Duplex w/ Terrace @ Box House Hotel,72991962259,verified,The Box House Hotel,Brooklyn,Greenpoint,40.73756,-73.95350,United States,US,False,strict,Hotel room,$907,$181,3.0,10.0
102061,35508488,"Cozy, clean Greenpoint room with yard access",74975156081,verified,Dawn,Brooklyn,Greenpoint,40.72516,-73.95004,United States,US,False,strict,Private room,$589,$118,30.0,38.0
102062,35509040,2BR XL Loft: Cleaning CDC guidelines implemented,85844415221,unconfirmed,Vida,Brooklyn,Greenpoint,40.72732,-73.94185,United States,US,False,flexible,Entire home/apt,$356,$71,30.0,13.0

In [23]:
df.drop_duplicates(inplace=True)

In [24]:
df.duplicated().sum()

0

### Handling missing / null Values

In [25]:
df.isna().sum()

ID                          0
NAME                      250
HOST ID                     0
HOST_IDENTITY_VERIFIED    289
HOST NAME                 404
NEIGHBOURHOOD GROUP        29
NEIGHBOURHOOD              16
LAT                         8
LONG                        8
COUNTRY                   532
COUNTRY CODE              131
INSTANT_BOOKABLE          105
CANCELLATION_POLICY        76
ROOM TYPE                   0
PRICE                     247
SERVICE FEE               273
MINIMUM NIGHTS            400
NUMBER OF REVIEWS         183
dtype: int64

In [26]:
df.dropna(inplace = True) #Dropping NA values

In [27]:
df.isna().sum()

ID                        0
NAME                      0
HOST ID                   0
HOST_IDENTITY_VERIFIED    0
HOST NAME                 0
NEIGHBOURHOOD GROUP       0
NEIGHBOURHOOD             0
LAT                       0
LONG                      0
COUNTRY                   0
COUNTRY CODE              0
INSTANT_BOOKABLE          0
CANCELLATION_POLICY       0
ROOM TYPE                 0
PRICE                     0
SERVICE FEE               0
MINIMUM NIGHTS            0
NUMBER OF REVIEWS         0
dtype: int64

### Further Improvemnts

In [29]:
df['HOST_IDENTITY_VERIFIED']=df['HOST_IDENTITY_VERIFIED'].str.upper()

In [30]:
df

,ID,NAME,HOST ID,HOST_IDENTITY_VERIFIED,HOST NAME,NEIGHBOURHOOD GROUP,NEIGHBOURHOOD,LAT,LONG,COUNTRY,COUNTRY CODE,INSTANT_BOOKABLE,CANCELLATION_POLICY,ROOM TYPE,PRICE,SERVICE FEE,MINIMUM NIGHTS,NUMBER OF REVIEWS
0,1001254,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,$966,$193,10.0,9.0
1,1002102,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,$142,$28,30.0,45.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,$204,$41,10.0,9.0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,$577,$115,3.0,74.0
7,1005202,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,57351953,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,$822,$164,1.0,9.0
102030,57352505,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,$455,$91,4.0,36.0
102031,57353057,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,"$1,078",$216,1.0,58.0
102032,57353610,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,$103,$21,7.0,40.0
102040,57358028,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,$982,$196,1.0,239.0

In [31]:
x = df['INSTANT_BOOKABLE'].apply(lambda x:1 if x==True else 0)

In [32]:
df['INSTANT_BOOKABLE'] = x

In [33]:
df

,ID,NAME,HOST ID,HOST_IDENTITY_VERIFIED,HOST NAME,NEIGHBOURHOOD GROUP,NEIGHBOURHOOD,LAT,LONG,COUNTRY,COUNTRY CODE,INSTANT_BOOKABLE,CANCELLATION_POLICY,ROOM TYPE,PRICE,SERVICE FEE,MINIMUM NIGHTS,NUMBER OF REVIEWS
0,1001254,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,$966,$193,10.0,9.0
1,1002102,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,$142,$28,30.0,45.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,$204,$41,10.0,9.0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,$577,$115,3.0,74.0
7,1005202,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,57351953,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,$822,$164,1.0,9.0
102030,57352505,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,$455,$91,4.0,36.0
102031,57353057,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,"$1,078",$216,1.0,58.0
102032,57353610,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,$103,$21,7.0,40.0
102040,57358028,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,$982,$196,1.0,239.0

In [34]:
df['INSTANT_BOOKABLE']

0         0
1         0
4         0
5         1
7         0
         ..
102029    0
102030    1
102031    1
102032    0
102040    1
Name: INSTANT_BOOKABLE, Length: 99508, dtype: int64

In [35]:
df.reset_index(inplace=True)

In [36]:
df

,index,ID,NAME,HOST ID,HOST_IDENTITY_VERIFIED,HOST NAME,NEIGHBOURHOOD GROUP,NEIGHBOURHOOD,LAT,LONG,COUNTRY,COUNTRY CODE,INSTANT_BOOKABLE,CANCELLATION_POLICY,ROOM TYPE,PRICE,SERVICE FEE,MINIMUM NIGHTS,NUMBER OF REVIEWS
0,0,1001254,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,$966,$193,10.0,9.0
1,1,1002102,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,$142,$28,30.0,45.0
2,4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,$204,$41,10.0,9.0
3,5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,$577,$115,3.0,74.0
4,7,1005202,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99503,102029,57351953,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,$822,$164,1.0,9.0
99504,102030,57352505,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,$455,$91,4.0,36.0
99505,102031,57353057,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,"$1,078",$216,1.0,58.0
99506,102032,57353610,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,$103,$21,7.0,40.0
99507,102040,57358028,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,$982,$196,1.0,239.0

In [37]:
# Removing $ symbol making it suitable for further analysis
df["PRICE"] = df['PRICE'].str.replace('[$,]','')

C:\Users\akash\AppData\Local\Temp\ipykernel_26468\2205588900.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df["PRICE"] = df['PRICE'].str.replace('[$,]','')

In [38]:
df['PRICE']

0         966
1         142
2         204
3         577
4        1060
         ...
99503     822
99504     455
99505    1078
99506     103
99507     982
Name: PRICE, Length: 99508, dtype: object

In [39]:
df["SERVICE FEE"] = df['SERVICE FEE'].str.replace('[$,]','')

C:\Users\akash\AppData\Local\Temp\ipykernel_26468\1148793471.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df["SERVICE FEE"] = df['SERVICE FEE'].str.replace('[$,]','')

In [40]:
df[["PRICE","SERVICE FEE"]]=df[["PRICE","SERVICE FEE"]].astype(int)

In [41]:
type(df['PRICE'][1])

numpy.int32

In [44]:
df.to_csv("C:\\Users\\akash\\OneDrive\\Desktop\\Python\\Airbnb Data Cleaning\\Cleaned Data.csv")#Exported as CSV